Add-form-to-portfolio
MILINDI7/personal_portfolio pull request #3
Opened 2022-08-24 21:44 UTC by MILINDI7

## What?
Add a submission form to your personal portfolio.

## Why?
As a portfolio will be accessed by different people with different purposes, it is a good idea to collect their information and interests.

## How?
By the use of labels and inputs as aspects of form, I created their skeleton in HTML and styled it in CSS.

2022-08-24 22:53 UTC, levy002 requested changes
## Hi @MILINDI7,  :wave: 
### I'm Levy, your PR reviewer

Excellent, you did a great job :sunglasses:
However, they are some issues that you need to address before you move on to the next project :wink:
![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)
## Highlights
- Good job for using the correct git-flow :heavy_check_mark: 
- All linters are passing :heavy_check_mark: 
- Descriptive README :heavy_check_mark: : 
### Status: REQUESTED CHANGES :recycle: 
_check my comments under review_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] [OPTIONAL] On your readme, you have the section "license" according to the [Microverse readme template](https://github.com/microverseinc/readme-template).  Kindly, make sure that The link featured in that section should points to a file at the root of your project (the license file).   Just copy it from the mentioned template:

![image](https://user-images.githubusercontent.com/57421823/168004669-c3026da8-8102-4a87-bb49-f7a5a9a6abbf.png)

That way, you will have a professional repo, and your project will be well documented 💪 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @levy002 in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 22:53 UTC, levy002 commented on index.html
> +          <form action="https://formspree.io/forms/mjvlqlvv/submissions" method="post">
- [ ] Kindly fix the `formspree` link because every time I try to send a message it provides an error. Please make sure that this form will be submitted successfully. :wink: 

   - ### Error message
  ![image](https://user-images.githubusercontent.com/87197412/186533676-94a2b85e-06b4-49e7-8980-7b218281ee67.png)

2022-08-24 22:53 UTC, levy002 commented on index.html
> +                <input type="text" name="user-name" id="name" value="text input" required>
- [ ] Kindly make sure that this name `input` has `maxlength="30"` validation as it is one of the mandatory project requirements. :wink:

2022-08-24 22:53 UTC, levy002 commented on index.html
> +                <textarea name="user-message" id="msg" cols="30" rows="10" required>Enter text here</textarea>
- [ ] Kindly make sure that the message `textarea` has `maxlength="500"` validation as it is one of the mandatory project requirements. wink

2022-08-24 22:53 UTC, levy002 commented on index.css
>  main {
- [ ] Kindly adjust your padding and margin on the `main` container because it seems that our whole element are not aligned correctly on the page, we have a huge space on the left side that is not needed. Please remove it in order to stick to the provided design. :wink: 

   - ### Your design
    
   ![image](https://user-images.githubusercontent.com/87197412/186534976-f9223b07-e084-430a-892d-a78d35f07a1e.png)

2022-08-24 22:53 UTC, levy002 commented on index.css
> +  margin-left: -35px;
- [ ] Kindly make sure to stick to the provided design while styling the form. Please go ahead and use the correct font and add the necessary spacing(margin and padding) on forms `input` and `textarea`. :100: 
   
   - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/186535753-5dedcdfb-7f6e-49de-b922-4c0acfced3b4.png)


   - ### Figma design
   ![image](https://user-images.githubusercontent.com/87197412/186535702-cef49d4d-0fff-44b5-b994-f453318d95cd.png)

2022-08-24 22:53 UTC, levy002 commented on index.css
> +}
- [ ] Kindly make sure to stick to the provided design by using the right colors, typography, and spacing while styling the form `submit` button. Please go ahead and implement the design according to the provided Figma design. :wink: 
- [ ] Kindly make to implement all button interactions (pressed, active, enabled) which will increase website user experience. :wink: 

  - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/186536732-a8198fbc-d65a-4bd0-9a2c-de95f36c8d00.png)


  - ### Figma design
  
   ![image](https://user-images.githubusercontent.com/87197412/186536690-cf7ddac8-f20f-42ec-a238-35d3399f3fe5.png)

  - ### Button interactions design
  
  ![image](https://user-images.githubusercontent.com/87197412/186536988-1244cfbc-fff6-41ae-949d-c81c146c576b.png)

2022-08-25 11:29 UTC, Nemwel-Boniface approved these changes
## Hello @MILINDI7               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 11:29 UTC, Nemwel-Boniface commented on index.html
> +                <textarea name="user-message" id="msg" maxlength="50" cols="30" rows="10" required>Enter text here</textarea>
- [ ] [OPTIONAL] It appears that you mistakenly forgot to place another zero. The max length is supposed to be 500 and not 50.

2022-08-25 11:29 UTC, Nemwel-Boniface commented on index.html
> +          <p class="footer-p">dshema7@gmail.com</p>
- [ ] [OPTIONAL] It would be better to make this section to stick to the chosen Figma design. Kindly consider to make this section to come to the middle section of the screen.

**This is how I am seeing it right now:**

![image](https://user-images.githubusercontent.com/86318284/186652807-802b6e57-ddaa-44c0-bbf9-db8d6034b852.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/186652885-23909252-3147-4fe2-a650-4e4ef1139c06.png)

2022-08-26 06:27 UTC, merged